
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASC ASTERISK AVG BAR BY CHART COMMA CUSTOM_METRIC DESC EQUALS FROM GRAPH GREATER_THAN GROUP IDENTIFIER LESS_THAN LIMIT LINE LPAREN NUMBER ORDER PIE PLOT RPAREN SELECT SEMICOLON STRING WHEREquery : SELECT select_list FROM IDENTIFIER where_clause group_by_clause plot_clause order_clause limit_clause SEMICOLONselect_list : ASTERISK\n                   | expression COMMA select_list\n                   | expressionexpression : IDENTIFIER\n                  | function_call\n                  | avg_function\n                  | custom_metricfunction_call : IDENTIFIER LPAREN arg_list RPARENavg_function : AVG LPAREN IDENTIFIER RPARENcustom_metric : CUSTOM_METRIC LPAREN IDENTIFIER COMMA arg_list RPARENarg_list : IDENTIFIER COMMA arg_list\n                | IDENTIFIERwhere_clause : WHERE condition\n                    | emptycondition : IDENTIFIER GREATER_THAN NUMBER\n                 | IDENTIFIER LESS_THAN NUMBER\n                 | IDENTIFIER EQUALS STRINGgroup_by_clause : GROUP BY IDENTIFIER\n                       | emptyorder_clause : ORDER BY IDENTIFIER order_direction\n                    | emptyorder_direction : ASC\n                       | DESClimit_clause : LIMIT NUMBER\n                    | emptyplot_clause : PLOT BAR GRAPH\n                   | PLOT LINE GRAPH\n                   | PLOT PIE CHART\n                   | emptyempty :'
    
_lr_action_items = {'SELECT':([0,],[2,]),'$end':([1,62,],[0,-1,]),'ASTERISK':([2,14,],[5,5,]),'IDENTIFIER':([2,12,13,14,15,16,24,26,29,40,58,],[4,17,18,4,21,22,34,18,18,51,64,]),'AVG':([2,14,],[10,10,]),'CUSTOM_METRIC':([2,14,],[11,11,]),'FROM':([3,4,5,6,7,8,9,20,27,28,44,],[12,-5,-2,-4,-6,-7,-8,-3,-9,-10,-11,]),'COMMA':([4,6,7,8,9,18,22,27,28,44,],[-5,14,-6,-7,-8,26,29,-9,-10,-11,]),'LPAREN':([4,10,11,],[13,15,16,]),'WHERE':([17,],[24,]),'GROUP':([17,23,25,33,52,53,54,],[-31,31,-15,-14,-16,-17,-18,]),'PLOT':([17,23,25,30,32,33,51,52,53,54,],[-31,-31,-15,38,-20,-14,-19,-16,-17,-18,]),'ORDER':([17,23,25,30,32,33,37,39,51,52,53,54,59,60,61,],[-31,-31,-15,-31,-20,-14,46,-30,-19,-16,-17,-18,-27,-28,-29,]),'LIMIT':([17,23,25,30,32,33,37,39,45,47,51,52,53,54,59,60,61,65,66,67,],[-31,-31,-15,-31,-20,-14,-31,-30,56,-22,-19,-16,-17,-18,-27,-28,-29,-21,-23,-24,]),'SEMICOLON':([17,23,25,30,32,33,37,39,45,47,51,52,53,54,55,57,59,60,61,63,65,66,67,],[-31,-31,-15,-31,-20,-14,-31,-30,-31,-22,-19,-16,-17,-18,62,-26,-27,-28,-29,-25,-21,-23,-24,]),'RPAREN':([18,19,21,35,36,],[-13,27,28,-12,44,]),'BY':([31,46,],[40,58,]),'GREATER_THAN':([34,],[41,]),'LESS_THAN':([34,],[42,]),'EQUALS':([34,],[43,]),'BAR':([38,],[48,]),'LINE':([38,],[49,]),'PIE':([38,],[50,]),'NUMBER':([41,42,56,],[52,53,63,]),'STRING':([43,],[54,]),'GRAPH':([48,49,],[59,60,]),'CHART':([50,],[61,]),'ASC':([64,],[66,]),'DESC':([64,],[67,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'select_list':([2,14,],[3,20,]),'expression':([2,14,],[6,6,]),'function_call':([2,14,],[7,7,]),'avg_function':([2,14,],[8,8,]),'custom_metric':([2,14,],[9,9,]),'arg_list':([13,26,29,],[19,35,36,]),'where_clause':([17,],[23,]),'empty':([17,23,30,37,45,],[25,32,39,47,57,]),'group_by_clause':([23,],[30,]),'condition':([24,],[33,]),'plot_clause':([30,],[37,]),'order_clause':([37,],[45,]),'limit_clause':([45,],[55,]),'order_direction':([64,],[65,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> SELECT select_list FROM IDENTIFIER where_clause group_by_clause plot_clause order_clause limit_clause SEMICOLON','query',10,'p_query','edsql_compiler.py',74),
  ('select_list -> ASTERISK','select_list',1,'p_select_list','edsql_compiler.py',78),
  ('select_list -> expression COMMA select_list','select_list',3,'p_select_list','edsql_compiler.py',79),
  ('select_list -> expression','select_list',1,'p_select_list','edsql_compiler.py',80),
  ('expression -> IDENTIFIER','expression',1,'p_expression','edsql_compiler.py',90),
  ('expression -> function_call','expression',1,'p_expression','edsql_compiler.py',91),
  ('expression -> avg_function','expression',1,'p_expression','edsql_compiler.py',92),
  ('expression -> custom_metric','expression',1,'p_expression','edsql_compiler.py',93),
  ('function_call -> IDENTIFIER LPAREN arg_list RPAREN','function_call',4,'p_function_call','edsql_compiler.py',97),
  ('avg_function -> AVG LPAREN IDENTIFIER RPAREN','avg_function',4,'p_avg_function','edsql_compiler.py',101),
  ('custom_metric -> CUSTOM_METRIC LPAREN IDENTIFIER COMMA arg_list RPAREN','custom_metric',6,'p_custom_metric','edsql_compiler.py',105),
  ('arg_list -> IDENTIFIER COMMA arg_list','arg_list',3,'p_arg_list','edsql_compiler.py',110),
  ('arg_list -> IDENTIFIER','arg_list',1,'p_arg_list','edsql_compiler.py',111),
  ('where_clause -> WHERE condition','where_clause',2,'p_where_clause','edsql_compiler.py',118),
  ('where_clause -> empty','where_clause',1,'p_where_clause','edsql_compiler.py',119),
  ('condition -> IDENTIFIER GREATER_THAN NUMBER','condition',3,'p_condition','edsql_compiler.py',123),
  ('condition -> IDENTIFIER LESS_THAN NUMBER','condition',3,'p_condition','edsql_compiler.py',124),
  ('condition -> IDENTIFIER EQUALS STRING','condition',3,'p_condition','edsql_compiler.py',125),
  ('group_by_clause -> GROUP BY IDENTIFIER','group_by_clause',3,'p_group_by_clause','edsql_compiler.py',130),
  ('group_by_clause -> empty','group_by_clause',1,'p_group_by_clause','edsql_compiler.py',131),
  ('order_clause -> ORDER BY IDENTIFIER order_direction','order_clause',4,'p_order_clause','edsql_compiler.py',135),
  ('order_clause -> empty','order_clause',1,'p_order_clause','edsql_compiler.py',136),
  ('order_direction -> ASC','order_direction',1,'p_order_direction','edsql_compiler.py',143),
  ('order_direction -> DESC','order_direction',1,'p_order_direction','edsql_compiler.py',144),
  ('limit_clause -> LIMIT NUMBER','limit_clause',2,'p_limit_clause','edsql_compiler.py',148),
  ('limit_clause -> empty','limit_clause',1,'p_limit_clause','edsql_compiler.py',149),
  ('plot_clause -> PLOT BAR GRAPH','plot_clause',3,'p_plot_clause','edsql_compiler.py',156),
  ('plot_clause -> PLOT LINE GRAPH','plot_clause',3,'p_plot_clause','edsql_compiler.py',157),
  ('plot_clause -> PLOT PIE CHART','plot_clause',3,'p_plot_clause','edsql_compiler.py',158),
  ('plot_clause -> empty','plot_clause',1,'p_plot_clause','edsql_compiler.py',159),
  ('empty -> <empty>','empty',0,'p_empty','edsql_compiler.py',163),
]
